server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          # Use the local git repo in the workspace as the configuration repository
          uri: file:///workspaces/doc-service/config-repo
         
          # The default branch created by init in this environment is `main`
          default-label: main
          # Do a local clone (no credentials) and allow it to be refreshed
          clone-on-start: true

